// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\Go\testovoe\internal\jwt_service\jwt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jwt_service "github.com/mikromolekula2002/Testovoe/internal/jwt_service"
)

// MockJWTService is a mock of JWTService interface.
type MockJWTService struct {
	ctrl     *gomock.Controller
	recorder *MockJWTServiceMockRecorder
}

// MockJWTServiceMockRecorder is the mock recorder for MockJWTService.
type MockJWTServiceMockRecorder struct {
	mock *MockJWTService
}

// NewMockJWTService creates a new mock instance.
func NewMockJWTService(ctrl *gomock.Controller) *MockJWTService {
	mock := &MockJWTService{ctrl: ctrl}
	mock.recorder = &MockJWTServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTService) EXPECT() *MockJWTServiceMockRecorder {
	return m.recorder
}

// CheckoutAccessToken mocks base method.
func (m *MockJWTService) CheckoutAccessToken(accessToken string, secretKey []byte) (*jwt_service.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutAccessToken", accessToken, secretKey)
	ret0, _ := ret[0].(*jwt_service.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckoutAccessToken indicates an expected call of CheckoutAccessToken.
func (mr *MockJWTServiceMockRecorder) CheckoutAccessToken(accessToken, secretKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutAccessToken", reflect.TypeOf((*MockJWTService)(nil).CheckoutAccessToken), accessToken, secretKey)
}

// GenerateAccessToken mocks base method.
func (m *MockJWTService) GenerateAccessToken(userID, ipAddress string, secretKey []byte, timeDuration int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID, ipAddress, secretKey, timeDuration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTServiceMockRecorder) GenerateAccessToken(userID, ipAddress, secretKey, timeDuration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTService)(nil).GenerateAccessToken), userID, ipAddress, secretKey, timeDuration)
}
