server:
  port: ":8080"       # Порт, на котором будет запускаться сервер

database:
  host: "insert_your_data"   # Адрес базы данных
  port: 5432          # Порт базы данных
  user: "insert_your_data"    # Имя пользователя базы данных
  password: "insert_your_data"  # Пароль пользователя базы данных
  dbname: "insert_your_data"    # Имя базы данных
  sslmode: "disable"
  

#может быть и не нужно это
logger:
  output: "stdout"  # Куда выводить логи: stdout или же file
  filepath: ""      # Путь где будут храниться логи, если выбран output "file"
  level: "debug"     # Уровни логирования: "debug", "info", "warn", "error"

#jwt token string
jwt:
  jwtkey: "insert_your_data" #Ваш секретный ключ для создания токенов

#Сервис отправки Email Warning
smtp_mail:
  smtp_auth_address:   "smtp.gmail.com" #Google mail smtp address(оставить так как есть, если почта google)
  smtp_server_address: "smtp.gmail.com:587" #Google mail auth smtp address(оставить так как есть, если почта google)
  smtp_name: "Auth Service API" #Имя отправителя, которое будет видеть получатель
  smtp_email_address: "insert_your_data" #Адрес отправителя
  smtp_email_password:  "insert_your_data" #16-значный код при работе с Google mail, с другой почтой может быть просто ваш пароль
